# Numpy 배열: 생성과 기본 특성

In [12]:
import numpy as np  #numpy 패키지 임포트

In [13]:
np.__version__      #버전확인

'1.14.3'

In [14]:
arr1 = np.array([1,3,5,7,9]) # 리스트를 사용하여 배열 생성

In [15]:
arr2 = np.array((1,3,5,7,9)) # 튜플 사용하여 배열 생성

In [16]:
type(arr1)  

numpy.ndarray

In [17]:
arr3=arr1

In [18]:
id(arr1)

2746756791952

In [19]:
id(arr3)

2746756791952

In [20]:
# arr1 과 arr3은 같은 메모리공간을 공유

In [21]:
arr4= arr1.copy # 얕은 복사

In [22]:
id(arr1)

2746756791952

In [23]:
id(arr4)

2746756871224

# arange 메서드

In [24]:
np.arange(10) # 0~9 범위

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(10,20) # 10에서 19범위

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
np.arange(10,20,3) # 10~ 19 사이를 3step

array([10, 13, 16, 19])

In [27]:
arr = np.arange(10)

In [28]:
len(arr)

10

In [29]:
arr.size

10

# linspace 메서드

In [30]:
np.linspace(0,10,5) # 0과 10 사이 5개의 그리드

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
arr = np.linspace(0,10,5, retstep=True) #스텝을 달고다님

In [32]:
type(arr)

tuple

In [33]:
arr[0] # 실제 배열

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
arr[1]

2.5

# zeros메서드

In [35]:
np.zeros(10) # 10개의 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,4)) # 3x4 행렬.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros(5,dtype='int64') # 자료형 명시

array([0, 0, 0, 0, 0], dtype=int64)

In [38]:
np.zeros(5,dtype='int64').dtype

dtype('int64')

# ones 메서드

In [39]:
arr = np.ones((2,3), dtype='int_')

In [40]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
arr.dtype

dtype('int32')

# Numpy배열: 원소의 자료형은 일치되어야 한다.

In [42]:
arr1 = np.array([111,2.3,True,False,False]) #숫자형과 불 원소 혼재

In [43]:
arr1 # 숫자형으로 자동 형변환

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [44]:
arr2 = np.array([111,2.3,'python','abc']) # 숫자형과 문자열 혼재

In [45]:
arr2 #문자열로 자동 변환

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [46]:
arr3 = np.array([111,True,'abc']) #숫자, 불, 문자열 혼재

In [47]:
arr3 #문자열로 자동 변환

array(['111', 'True', 'abc'], dtype='<U11')

# Numpy 배열의 슬라이싱(slicing)

In [48]:
a = np.array([1,2,3,4,5]) # 1D 배열.

In [49]:
a[:2]

array([1, 2])

In [50]:
a[-1] # 끝에서 첫번째 원소

5

In [51]:
a[:] # 전체!

array([1, 2, 3, 4, 5])

In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])# 3x3 행렬

In [53]:
a[1]

array([4, 5, 6])

In [54]:
a[-1]

array([7, 8, 9])

In [55]:
a[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Numpy 배열의 모양

In [56]:
a.size #원소의 갯수.

9

In [57]:
a.shape # 전체적인 모양(shape)

(3, 3)

In [58]:
a.ndim #디멘션 수

2

In [59]:
a = np.arange(15) # 0~ 14 전체 15개의 원소 1D배열

In [60]:
a.reshape(3,5)   # 3행 5열 2D 행렬로 일시적으로 바꾸어 보여줌

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
a.shape = (3,5) # 3x5모양의 2D 행렬로 바꾸어줌(영구적)

In [63]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Numpy 배열의 모양 (주의)

In [64]:
a = np.array([2,5,1,3])

In [65]:
a.shape # rank 1 배열, 백터는 아님

(4,)

In [66]:
a = a.reshape(4,1) # 이제는 컬럼백터.

In [67]:
a

array([[2],
       [5],
       [1],
       [3]])

In [68]:
a.shape

(4, 1)

In [69]:
a = np.arange(10) # 0~9, 전체 10개의 원소, 1D 배열.

In [70]:
b = a.reshape(2,5) # 2x5 모양의 2D 행렬

In [71]:
a[0] = -999 # 배열 a의 인덱스 0번의 값을 변경

In [72]:
b # 메모리 공간 공유

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [73]:
 c = a.reshape(2,5).copy() #얉은 복사로 새로운 객체 만듬

In [74]:
c[0,0] = 0

In [75]:
a # 메모리 공간이 다르기 때문에 아무런 영향이 없음

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

# Numpy 로직 배열 활용 필터링

In [76]:
arr = np.arange(100)    # 0~99

In [77]:
arrMask = ((arr % 5) == 0) #로직배열. 5의 배수인 경우 True.

In [78]:
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [79]:
arrMask = (((arr % 5)==0) & (arr > 0)) #배열에서 0을 제거

In [80]:
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

# Numpy 배열의 확장

In [81]:
a = np.array([1,2,3])

In [82]:
b = np.append(a,[4,5,6])

In [83]:
b

array([1, 2, 3, 4, 5, 6])

In [84]:
a=np.array([[1,2],[3,4]])

In [85]:
c=np.array(([3,5],[6,7]))

In [86]:
c

array([[3, 5],
       [6, 7]])

In [87]:
a

array([[1, 2],
       [3, 4]])

In [88]:
b=np.append(a,[[9,9]],axis=0) #새로운 행으로 추가 a에는 효과없음

In [89]:
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [90]:
a

array([[1, 2],
       [3, 4]])

In [91]:
c=np.append(a,[[9],[9]],axis=1) #새로운 열로 추가 a에는 효과없음

In [92]:
c

array([[1, 2, 9],
       [3, 4, 9]])

In [93]:
c

array([[1, 2, 9],
       [3, 4, 9]])

In [94]:
a = np.array([[1,2,3],[4,5,6]])

In [95]:
np.delete(a,0)  # 인덱스 값삭제 (일시적)

array([2, 3, 4, 5, 6])

In [96]:
np.delete(a,(0,2,4))

array([2, 4, 6])

In [97]:
np.delete(a,1,axis =0) # 행 전체 삭제(일시적)

array([[1, 2, 3]])

In [98]:
np.delete(a,1,axis=1) # 열 전체 삭제(일시적)

array([[1, 3],
       [4, 6]])

In [99]:
a

array([[1, 2, 3],
       [4, 5, 6]])

# NUMPY의 연산

In [100]:
#리스트연산과 NUMPY 배열의 연산비교 "+" 연산자

In [101]:
a=[1,2,3] # 리스트의 경우 "+"는 리스트의 연결을 의미
b=[4,5,6]

In [102]:
a + b

[1, 2, 3, 4, 5, 6]

In [103]:
a = np.array([1,2,3]) #numpy의 경우 "+"는 원소별 연산의 의미
b = np.array([4,5,6])

In [104]:
a+b

array([5, 7, 9])

In [105]:
#리스트 연산과 NUMPY 배열의 연산비교: '*'연산자

In [106]:
a = [1,2,3] #리스트의 경우 '*' 리스트의 반복을 의미
3 * a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [107]:
b = np.array([1,2,3]) # Numpy의 경우는 원소별 연산을 의미
3 * b

array([3, 6, 9])

In [108]:
#NUMPY배열의 연산

In [109]:
a= np.array([1,2,3])
b= np.array([4,5,6])
a+b

array([5, 7, 9])

In [110]:
b - a #b의 원소와 a 의 원소 '-'' 연산

array([3, 3, 3])

In [111]:
a * b # a의 원소와 b의 연소 곱셈

array([ 4, 10, 18])

In [112]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

# NUMPY 배열의 연산: 백터화

In [113]:
x = np.array([0,1,2,3])

In [114]:
pow(10,x) #10의 X승 연산

array([   1,   10,  100, 1000], dtype=int32)

In [115]:
x**3 #x의 3승 연산

array([ 0,  1,  8, 27], dtype=int32)

In [116]:
np.exp(x) #지수함수의 x승

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [117]:
myFunctions(x) # 사용자 정의함수

NameError: name 'myFunctions' is not defined

In [118]:
#메서드로 제공되는 통계함수

In [119]:
x = np .arange(1,11)

In [120]:
x.sum() #배열의 원소의 합

55

In [121]:
 x.mean()# 배열의 평균

5.5

In [122]:
x.std() #배열의 표준편차

2.8722813232690143

In [123]:
x.var() #배열의 분산

8.25

In [124]:
x.cumsum() # 배열의 누적배열

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [125]:
#메서드로 제공되는 통계 함수

In [126]:
x = np.arange(1,10)
x = x.reshape((3,-1)) #(3,-1)은 (3,3)을 의미 자동으로 맞춰서 만들어줌

In [127]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:
print(x.mean(axis=0)) #열의 평균

[4. 5. 6.]


In [129]:
print(x.mean(axis=1)) #행의 평균

[2. 5. 8.]


In [130]:
np.random.seed(123)

In [131]:
x = np.random.randint(10, size=1000) # 

In [132]:
x.max

<function ndarray.max>

In [133]:
x.min()

0

In [134]:
(x>5).sum() #5보다 작은 숫자의 수

401

In [135]:
np.unique(x) #유니크한 값만 가져온다

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
sorted(set(x)) #set으로 유니크한 값을 만들고 순서대로 정렬한다.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# NUMPY 선형 대수학

In [137]:
x = np.array([1,3,5])
y = np.array([2,4,6])

In [138]:
x * y # x의 배열과 y의 배열을 같은 자리의 원소들끼리 곱한다.

array([ 2, 12, 30])

In [139]:
np.sum(x*y) # x와 y의 배열의 곱의 합

44

In [140]:
np.dot(x,y) #벡터 x와 y 사이의 내적을 구한다.

44

In [141]:
x = np.array([1,3,5])
y = np.array([2,4,6])
x = x.reshape((3,1))
y = y.reshape((1,3))
y.dot(x) # 하나의 원소를 갖는 행렬의곱
x.dot(y)

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

In [142]:
np.zeros((2,3)) # 원소가 0인 2,3 행렬

array([[0., 0., 0.],
       [0., 0., 0.]])

In [143]:
np.ones((2,3)) # 원소가 0dls 2,3행렬

array([[1., 1., 1.],
       [1., 1., 1.]])

In [144]:
np.random.seed() # 랜덤 시드 초기화 (n =seed)

In [145]:
np.random.random((2,2)) # 0과 1사이 균등분포 (uniform) 랜덤 행렬, 튜플 두겹  np.random.random

array([[0.10015789, 0.67021182],
       [0.69271466, 0.24434791]])

In [146]:
np.random.randn(2,2) # 정규분포 랜덤 행렬, 튜플 한겹 np.random.randn

array([[-0.77950036, -2.53952779],
       [ 1.12709744,  1.08239074]])

In [147]:
m = np.diag([1,2,3]) # 대각행렬

In [148]:
m

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [149]:
np.diag(m) # 행렬의 대각선상의 원소 배열을 생성

array([1, 2, 3])

In [150]:
m1 = np.array([[1,2,3],[4,5,6]])# 크기가 2x3인 행렬
m2 = np.array([[6,5,4],[3,2,1]])# 크기가 2x3인 행렬

In [151]:
m1+m2 #행렬의 덧셈

array([[7, 7, 7],
       [7, 7, 7]])

In [152]:
m1-m2 #행렬의 뺄셈

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [153]:
m1 * m2

array([[ 6, 10, 12],
       [12, 10,  6]])

In [155]:
np.dot(m1,m2) # 사이즈 오류 발생

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [156]:
np.transpose(m2) # m2행렬을 3x2로 변경함

array([[6, 3],
       [5, 2],
       [4, 1]])

In [157]:
np.dot(m1, np.transpose(m2)) # 선형대수학 곱셈 계산

array([[28, 10],
       [73, 28]])

In [159]:
a = np.array([[1,2,3]])
b = np.array([[4],
            [5],
            [6]])

In [160]:
np.dot(a,b) # 선형대수학 공식에서 곱셈의 계산은 앞에 있는 행렬의 열값과 뒤에 있는 행렬의 행의 수가 같아야한다.! 
            # 엄청나게 중요하거임.

array([[32]])

In [161]:
m =np.array([[1,2],[3,4]])

In [162]:
3 * m # 스칼라(벡터와 달리 크기만 있고 방향값이 없는 양 )와 행렬의 곱

array([[ 3,  6],
       [ 9, 12]])

In [164]:
m / 2.0 # 스칼라와 행렬의 나눗셈

array([[0.5, 1. ],
       [1.5, 2. ]])

In [168]:
m = np.array([[1,2],[3,4]]) # 정사가격 shape의 행렬
minv = np.linalg.inv(m) #  m의 역행렬

In [169]:
minv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [172]:
mres = np.dot(m,minv) # 역행렬의 곱셈
np.round(mres,2) #단위행렬

array([[1., 0.],
       [0., 1.]])

In [194]:
A = np.array([[5,8],[6,4]]) #정사각형 shape의 행렬

In [195]:
B = np.array([[30],[25]])

In [196]:
Ainv =np.linalg.inv(A)
Ainv

array([[-0.14285714,  0.28571429],
       [ 0.21428571, -0.17857143]])

In [197]:
np.dot(Ainv,B) #x의 시간당 생산량, y의 시간당 생산량

array([[2.85714286],
       [1.96428571]])

In [198]:
np.linalg.solve(A,B) #Numpy의 linal.solve 메서드를 사용해서 구함.

array([[2.85714286],
       [1.96428571]])